# Generated by Django 4.1.6 on 2023-03-06 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_value', models.CharField(blank=True, default='', max_length=8, unique=True)),
                ('url', models.URLField(max_length=600)),
                ('exp_date', models.DateTimeField(blank=True, null=True)),
                ('date_added', models.DateTimeField(verbose_name=datetime.datetime(2023, 3, 6, 7, 5, 9, 70714, tzinfo=datetime.timezone.utc))),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
