# Generated by Django 4.1.6 on 2023-03-06 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petiteurl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 3, 6, 7, 7, 8, 485461, tzinfo=datetime.timezone.utc)),
        ),
    ]
