# Generated by Django 4.1.6 on 2023-02-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petiteurl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='exp_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
