# Generated by Django 4.1.6 on 2023-03-06 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petiteurl', '0002_alter_urls_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 6, 7, 10, 2, 879110, tzinfo=datetime.timezone.utc)),
        ),
    ]
