# Generated by Django 4.1.6 on 2023-02-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petiteurl', '0003_alter_urls_exp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='exp_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
